ayur/ayur/urls.py
from django.conf import settings
from django.conf.urls.static import static
from user import views
from django.contrib import admin
from django.urls import path
from django.urls import path, include
urlpatterns = [
    path('',views.HomePage,name = "home"),
    path('about',views.aboutPage,name = "about"),
    path('admin/', admin.site.urls),
    path('user/', include('user.urls')),
    path('expenses/',include('expenses.urls')),
    path('hospital/',include('hospital.urls'))
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT) 

ayur/user/urls.py
from django.urls import path
from . import views

app_name = "user"

urlpatterns = [
    path('reg/', views.registerPage, name='register'),
    path('login/', views.loginPage, name='login'),
    path('logout/', views.logoutUser, name="logout"),
]

ayur/user/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
# Create your models here.

# Create your models here.
class User(AbstractUser):
    first_name = models.CharField(max_length=100)
    last_name = models.CharField(max_length=100)
    phone_no=models.CharField(max_length=10)
    def __str__(self) -> str:
        return str(self.first_name)

ayur/user/forms.py
from django.forms import ModelForm
from django.contrib.auth.forms import UserCreationForm
from .models import User
from django import forms


class CreateUserForm(UserCreationForm):
	class Meta:
		model = User
		fields = ['username', 'email', 'password1', 'password2','first_name','last_name','phone_no']

ayur/user/views.py
from django.shortcuts import render

# Create your views here.
from django.shortcuts import render, redirect 
from django.http import HttpResponse
from django.forms import inlineformset_factory
from django.contrib.auth.forms import UserCreationForm

from django.contrib.auth import authenticate, login, logout

from django.contrib import messages
from .forms import  CreateUserForm

from django.contrib.auth.decorators import login_required

# Create your views here.
from .models import *
def HomePage(request):
    return render(request,'user/index.html',{})

def aboutPage(request):
    return render(request,'user/about.html',{})

def registerPage(request):
	if request.user.is_authenticated:
		return redirect('home')
	else:
		form = CreateUserForm()
		if request.method == 'POST':
			form = CreateUserForm(request.POST)
			if form.is_valid():
				form.save()
				user = form.cleaned_data.get('username')
				messages.success(request, 'Account was created for ' + user)

				return redirect('user:login')
			

		context = {'form':form}
		return render(request, 'user/register.html', context)

def loginPage(request):
	if request.user.is_authenticated:
		return redirect('home')
	else:
		if request.method == 'POST':
			username = request.POST.get('username')
			password =request.POST.get('password')

			user = authenticate(request, username=username, password=password)

			if user is not None:
				login(request, user)
				return redirect('home')
			else:
				messages.info(request, 'Username OR password is incorrect')

		context = {}
		return render(request, 'user/login.html', context)

def logoutUser(request):
	logout(request)
	return redirect('user:login')

ayur/user/templates/user/about.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
<title>About us</title>
{% comment %} {% static 'plugins/font-awesome-4.7.0/css/font-awesome.min.css' %} {% endcomment %}
<meta charset="utf-8">
<meta http-equiv="X-UA-Compatible" content="IE=edge">
<meta name="description" content="SportFIT template project">
<meta name="viewport" content="width=device-width, initial-scale=1">
<link rel="stylesheet" type="text/css" href="{% static 'styles/bootstrap-4.1.2/bootstrap.min.css' %}">
<link href="{% static 'plugins/font-awesome-4.7.0/css/font-awesome.min.css' %}" rel="stylesheet" type="text/css">
<link rel="stylesheet" type="text/css" href="{% static 'plugins/OwlCarousel2-2.2.1/owl.carousel.css' %}">
<link rel="stylesheet" type="text/css" href="{% static 'plugins/OwlCarousel2-2.2.1/owl.theme.default.css' %}">
<link rel="stylesheet" type="text/css" href="{% static 'plugins/OwlCarousel2-2.2.1/animate.css' %}">
<link href="{% static 'plugins/colorbox/colorbox.css' %}" rel="stylesheet" type="text/css">
<link rel="stylesheet" type="text/css" href="{% static 'styles/about.css' %}">
<link rel="stylesheet" type="text/css" href="{% static 'styles/about_responsive.css' %}">
</head>
<body>

<div class="super_container">
	
	<!-- Header -->

	<header class="header">
		<div class="container">
			<div class="row">
				<div class="col">
					<div class="header_content d-flex flex-row align-items-center justify-content-start trans_400">
						<a href="#">
							<div class="logo d-flex flex-row align-items-center justify-content-start"><img src="{% static 'images/dot.png' %}" alt=""><div>AYUR<span></span></div></div>
						</a>
						<nav class="main_nav">
							<ul class="d-flex flex-row align-items-center justify-content-start">
								<li><a href="{% url 'home'%}">Home</a></li>
								<li class="active"><a href="{% url 'about'%}">About us</a></li>
								<li><a href="services.html">Classes & Services</a></li>
								<li><a href="blog.html">Blog</a></li>
								{% comment %} <li><a href="contact.html">Contact</a></li> {% endcomment %}
							</ul>
						</nav>
						<div class="phone d-flex flex-row align-items-center justify-content-start ml-auto">
							<i class="fa fa-phone" aria-hidden="true"></i>
							<div>+91 1234567890</div>
						</div>
					</div>
				</div>
			</div>
		</div>
	</header>

	<!-- Hamburger -->
	
	<div class="hamburger_bar trans_400 d-flex flex-row align-items-center justify-content-start">
		<div class="hamburger">
			<div class="menu_toggle d-flex flex-row align-items-center justify-content-start">
				<span>menu</span>
				<div class="hamburger_container">
					<div class="menu_hamburger">
						<div class="line_1 hamburger_lines" style="transform: matrix(1, 0, 0, 1, 0, 0);"></div>
						<div class="line_2 hamburger_lines" style="visibility: inherit; opacity: 1;"></div>
						<div class="line_3 hamburger_lines" style="transform: matrix(1, 0, 0, 1, 0, 0);"></div>
					</div>
				</div>
			</div>
		</div>
	</div>

	<!-- Menu -->

	<div class="menu trans_800">
		<div class="menu_content d-flex flex-column align-items-center justify-content-center text-center">
			<ul>
				<li><a href="{% url 'home'%}">Home</a></li>
				<li><a href="{% url 'about'%}">About us</a></li>
				<li><a href="services.html">Classes & Services</a></li>
				<li><a href="blog.html">Blog</a></li>
				{% comment %} <li><a href="contact.html">Contact</a></li> {% endcomment %}
			</ul>
		</div>
		<div class="menu_phone d-flex flex-row align-items-center justify-content-start">
			<i class="fa fa-phone" aria-hidden="true"></i>
				<span>+91 1234567890</span>
		</div>
	</div>

	<!-- Home -->

	<div class="home">
		<div class="background_image" style="background-image:url({% static 'images/about_page.jpg' %})"></div>
		<div class="overlay"></div>
		<div class="home_container">
			<div class="container">
				<div class="row">
					<div class="col">
						<div class="home_content">
							<div class="home_title">About us</div>
							<div class="home_subtitle">Diet Plan,Fitness, Expense Tracker & many more</div>
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>

	<!-- About -->

	<div class="about">
		<div class="container about_container">
			<div class="row">
				<div class="col-lg-6">
					<div class="about_content">
						<div class="section_title_container">
							<div class="section_subtitle">welcome to Ayur</div>
							<div class="section_title">About <span>Ayur</span></div>
						</div>
						<div class="text_highlight"> “To ensure good health: eat lightly, breathe deeply, live moderately, cultivate cheerfulness, and maintain an interest in life.” – William Londen .</div>
						<div class="about_text">
							<p>The Ayur Health-Care System is a new, self-contained product, that replaces the current system of fitness apps that are unintuitive, not interactive, i.e. no real-time feedback to the users. Our main aim is to make people realize the importance of staying healthy and fit during the pandemic.
								Implement a digital health e-wallet application that keeps a track of various features related to diet plans, health expenses, workout routines etc. This product is a website intended to make fitness journeys intuitive, interactive, and free.
								</p>
						</div>
						<div class="button about_button"><a href="#">Join Now</a></div>
					</div>
				</div>
			</div>
		</div>
		<div class="about_background">
			<div class="about_image"><img src="{% static 'images/a2.png' %}" alt=""></div>
		</div>
	</div>

	<!-- Team -->

	<div class="team">
		<div class="parallax_background parallax-window" data-parallax="scroll" data-image-src="images/blog.jpg" data-speed="0.8"></div>
		<div class="container">
			<div class="row">
				<div class="col-lg-6">
					<div class="section_title_container">
						<div class="section_subtitle">welcome to Ayur</div>
						<div class="section_title">The Team</div>
					</div>
				</div>
			</div>
			<div class="row team_row">
				
				<!-- Team Member -->
				<div class="col-lg-4 team_col">
					<div class="team_item">
						<div class="team_image"><img src="{% static 'images/fit10.PNG' %}" alt=""></div>
						<div class="team_panel d-flex flex-column align-items-center justify-content-center text-center">
							<div class="team_name"><a href="#">Prachi</a></div>
							<div class="team_title">Trainer</div>
						</div>
					</div>
				</div>

				<!-- Team Member -->
				<div class="col-lg-4 team_col">
					<div class="team_item">
						<div class="team_image"><img src="{% static 'images/fit10.PNG' %}" alt=""></div>
						<div class="team_panel d-flex flex-column align-items-center justify-content-center text-center">
							<div class="team_name"><a href="#">Pranjal</a></div>
							<div class="team_title">Trainer</div>
						</div>
					</div>
				</div>

				<!-- Team Member -->
				<div class="col-lg-4 team_col">
					<div class="team_item">
						<div class="team_image"><img src="{% static 'images/fit10.PNG' %}" alt=""></div>
						<div class="team_panel d-flex flex-column align-items-center justify-content-center text-center">
							<div class="team_name"><a href="#">Sonali</a></div>
							<div class="team_title">Trainer</div>
						</div>
					</div>
				</div>

			</div>
		</div>
	</div>

	<!-- Skills -->

	<div class="skills">
		<div class="container">
			<div class="row row-lg-eq-height">
				
				<!-- Extra -->
				<div class="col-lg-6">
					<div class="extra d-flex flex-column align-items-center justify-content-center text-center">
						<div class="background_image" style="background-image:url(images/extra.jpg)"></div>
						<div class="extra_title">15% Discount</div>
						<div class="extra_text">
							<p>Morbi sed varius risus, vitae molestie lectus. Donec id hendrerit velit, eu fringilla neque. Etiam id finibus sapien. Donec sollicitudin luctus ex non pharetra.llus.</p>
						</div>
						<div class="button extra_button"><a href="#">Join Now</a></div>
					</div>
				</div>

				<!-- Skills -->
				<div class="col-lg-6 skills_col">
					<div class="skills_content">
						<div class="section_title_container">
							<div class="section_subtitle">welcome to Ayur</div>
							<div class="section_title">We love sport</div>
						</div>
						<div class="skills_text">
							<p>Morbi sed varius risus, vitae molestie lectus. Donec id hendrerit velit, eu fringilla neque. Etiam id finibus sapien. Donec sollicitudin luctus ex non pharetra. Aenean lobortis ut leo vel porta. Maecenas ac vestibulum lectus. Cras nulla urna, lacinia ut tempor facilisis, congue dignissim tellus. Maecenas ac vestibulum lectus. Cras nulla urna, lacinia ut tempor facilisis, congue dignissim tellus. Phasellus sit amet justo ullamcorper, elementum ipsum nec, vulputate neque.</p>
						</div>

						<!-- Progress Bars -->
						<ul class="progress_bar_container col_12 clearfix">
							<li class="pb_item">
								<div id="skill_1_pbar" class="skill_bars" data-perc="1.00" data-name="skill_1_pbar"></div>
								<h5>Fitness</h5>
							</li>
							<li class="pb_item">
								<div id="skill_2_pbar" class="skill_bars" data-perc="0.70" data-name="skill_2_pbar"></div>
								<h5>Pilates</h5>
							</li>
							<li class="pb_item">
								<div id="skill_3_pbar" class="skill_bars" data-perc="0.85" data-name="skill_3_pbar"></div>
								<h5>Yoga</h5>
							</li>
							<li class="pb_item">
								<div id="skill_4_pbar" class="skill_bars" data-perc="0.95" data-name="skill_4_pbar"></div>
								<h5>Aerobics</h5>
							</li>
						</ul>

					</div>
				</div>
			</div>
		</div>
	</div>

	<!-- Footer -->

	<footer class="footer">
		<div class="container">
			<div class="row">
				<div class="col-lg-8 offset-lg-2">
					<div class="footer_container">
						<div class="footer_content">
							<div class="footer_logo">
								<a href="#">
									<div class="logo d-flex flex-row align-items-center justify-content-center"><img src="{% static 'images/dot.png' %}" alt=""><div>AYUR<span></span></div></div>
								</a>
							</div>
							<nav class="footer_nav">
								<ul class="d-flex flex-sm-row flex-column align-items-sm-start align-items-center justify-content-center">
									<li><a href="{% url 'home'%}">Home</a></li>
									<li><a href="{% url 'about'%}">About us</a></li>
									<li><a href="services.html">Our Services</a></li>
									<li><a href="blog.html">Blog</a></li>
									{% comment %} <li><a href="contact.html">Contact</a></li> {% endcomment %}
								</ul>
							</nav>
							<div class="newsletter_container">
								<form action="#" id="newsletter_form" class="newsletter_form">
									<input type="text" class="newsletter_input" placeholder="Enter your email here" required="required">
									<button class="newsletter_button">go</button>
								</form>
							</div>
							<div class="copyright d-flex flex-row align-items-start justify-content-sm-end justify-content-center"><!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->
Copyright &copy;<script>document.write(new Date().getFullYear());</script> All rights reserved | This template is made with <i class="fa fa-heart-o" aria-hidden="true"></i> by <a href="https://colorlib.com" target="_blank">Colorlib</a>
<!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. --></div>
						</div>
						<div class="footer_image text-center"><img src="{% static 'images/footer.png' %}" alt=""></div>
					</div>
				</div>
			</div>
		</div>
	</footer>
</div>

<script src="{% static 'js/jquery-3.2.1.min.js' %}"></script>
<script src="{% static 'styles/bootstrap-4.1.2/popper.js' %}"></script>
<script src="{% static 'styles/bootstrap-4.1.2/bootstrap.min.js' %}"></script>
<script src="{% static 'plugins/greensock/TweenMax.min.js' %}"></script>
<script src="{% static 'plugins/greensock/TimelineMax.min.js' %}"></script>
<script src="{% static 'plugins/scrollmagic/ScrollMagic.min.js' %}"></script>
<script src="{% static 'plugins/greensock/animation.gsap.min.js' %}"></script>
<script src="{% static 'plugins/greensock/ScrollToPlugin.min.js' %}"></script>
<script src="{% static 'plugins/OwlCarousel2-2.2.1/owl.carousel.js' %}"></script>
<script src="{% static 'plugins/easing/easing.js' %}"></script>
<script src="{% static 'plugins/progressbar/progressbar.min.js' %}"></script>
<script src="{% static 'plugins/parallax-js-master/parallax.min.js' %}"></script>
<script src="{% static 'plugins/colorbox/jquery.colorbox-min.js' %}"></script>
<script src="{% static 'js/about.js' %}"></script>
</body>
</html>

ayur/user/templates/user/contact.html
<!DOCTYPE html>
<html lang="en">
<head>
<title>Contact</title>
<meta charset="utf-8">
<meta http-equiv="X-UA-Compatible" content="IE=edge">
<meta name="description" content="SportFIT template project">
<meta name="viewport" content="width=device-width, initial-scale=1">
<link rel="stylesheet" type="text/css" href="styles/bootstrap-4.1.2/bootstrap.min.css">
<link href="plugins/font-awesome-4.7.0/css/font-awesome.min.css" rel="stylesheet" type="text/css">
<link rel="stylesheet" type="text/css" href="styles/contact.css">
<link rel="stylesheet" type="text/css" href="styles/contact_responsive.css">
</head>
<body>

<div class="super_container">
	
	<!-- Header -->

	<header class="header">
		<div class="container">
			<div class="row">
				<div class="col">
					<div class="header_content d-flex flex-row align-items-center justify-content-start trans_400">
						<a href="#">
							<div class="logo d-flex flex-row align-items-center justify-content-start"><img src="images/dot.png" alt=""><div>AYUR<span></span></div></div>
						</a>
						<nav class="main_nav">
							<ul class="d-flex flex-row align-items-center justify-content-start">
								<li><a href="index.html">Home</a></li>
								<li><a href="about.html">About us</a></li>
								<li><a href="services.html">Classes & Services</a></li>
								<li><a href="blog.html">Blog</a></li>
								<li class="active"><a href="contact.html">Contact</a></li>
							</ul>
						</nav>
						<div class="phone d-flex flex-row align-items-center justify-content-start ml-auto">
							<i class="fa fa-phone" aria-hidden="true"></i>
							<div>+91 1234567890</div>
						</div>
					</div>
				</div>
			</div>
		</div>
	</header>

	<!-- Hamburger -->
	
	<div class="hamburger_bar trans_400 d-flex flex-row align-items-center justify-content-start">
		<div class="hamburger">
			<div class="menu_toggle d-flex flex-row align-items-center justify-content-start">
				<span>menu</span>
				<div class="hamburger_container">
					<div class="menu_hamburger">
						<div class="line_1 hamburger_lines" style="transform: matrix(1, 0, 0, 1, 0, 0);"></div>
						<div class="line_2 hamburger_lines" style="visibility: inherit; opacity: 1;"></div>
						<div class="line_3 hamburger_lines" style="transform: matrix(1, 0, 0, 1, 0, 0);"></div>
					</div>
				</div>
			</div>
		</div>
	</div>

	<!-- Menu -->

	<div class="menu trans_800">
		<div class="menu_content d-flex flex-column align-items-center justify-content-center text-center">
			<ul>
				<li><a href="index.html">Home</a></li>
				<li><a href="about.html">About us</a></li>
				<li><a href="services.html">Classes & Services</a></li>
				<li><a href="blog.html">Blog</a></li>
				<li><a href="contact.html">Contact</a></li>
			</ul>
		</div>
		<div class="menu_phone d-flex flex-row align-items-center justify-content-start">
			<i class="fa fa-phone" aria-hidden="true"></i>
				<span>+91 1234567890</span>
		</div>
	</div>

	<!-- Home -->

	<div class="home">
		<div class="background_image" style="background-image:url(images/contact.jpg)"></div>
		<div class="overlay"></div>
		<div class="home_container">
			<div class="container">
				<div class="row">
					<div class="col">
						<div class="home_content">
							<div class="home_title">Contact</div>
							<div class="home_subtitle">Diet Plan,Fitness, Expense Tracker & many more</div>
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>

	<!-- Contact -->

	<div class="contact">
		<div class="container">
			<div class="row">

				<!-- Contact Content -->
				<div class="col-lg-4">
					<div class="contact_content">
						<div class="contact_logo">
							<div class="logo d-flex flex-row align-items-center justify-content-start"><img src="images/dot.png" alt=""><div>AYUR<span></span></div></div>
						</div>
						<div class="contact_text">
							<p> contact us for any sort of query.</p>
						</div>
						<div class="contact_list">
							<ul>
								<li class="d-flex flex-row align-items-start justify-content-start">
									<div><div>A:</div></div>
									<div>xyz , colaba ,mumbai -400005</div>
								</li>
								<li class="d-flex flex-row align-items-start justify-content-start">
									<div><div>P:</div></div>
									<div>+91 1234567890</div>
								</li>
								<li class="d-flex flex-row align-items-start justify-content-start">
									<div><div>M:</div></div>
									<div>yourmail@gmail.com</div>
								</li>
							</ul>
						</div>
					</div>
				</div>

				<!-- Contact Form -->
				<div class="col-lg-8 contact_col">
					<div class="contact_title">Get in touch</div>
					<div class="contact_form_container">
						<form action="#" id="contact_form" class="contact_form">
							<div class="row">
								<div class="col-lg-6">
									<div class="input_item"><input type="text" class="contact_input trans_200" placeholder="Name" required="required"></div>
								</div>
								<div class="col-lg-6">
									<div class="input_item"><input type="email" class="contact_input trans_200" placeholder="E-mail" required="required"></div>
								</div>
							</div>
							<div class="input_item"><textarea class="contact_input contact_textarea trans_200" placeholder="Message" required="required"></textarea></div>
							<button class="contact_button button">Send<span></span></button>
						</form>
					</div>
				</div>

			</div>
			<div class="row google_map_row">
				<div class="col">
					
					<!-- Contact Map -->

					<div class="contact_map">

						<!-- Google Map -->
						
						<div class="map">
							<div id="google_map" class="google_map">
								<div class="map_container">
									<div id="map"></div>
								</div>
							</div>
						</div>

					</div>

				</div>
			</div>
		</div>
	</div>

	<!-- Footer -->

	<footer class="footer">
		<div class="container">
			<div class="row">
				<div class="col-lg-8 offset-lg-2">
					<div class="footer_container">
						<div class="footer_content">
							<div class="footer_logo">
								<a href="#">
									<div class="logo d-flex flex-row align-items-center justify-content-center"><img src="images/dot.png" alt=""><div>AYUR<span></span></div></div>
								</a>
							</div>
							<nav class="footer_nav">
								<ul class="d-flex flex-sm-row flex-column align-items-sm-start align-items-center justify-content-center">
									<li><a href="index.html">Home</a></li>
									<li><a href="about.html">About us</a></li>
									<li><a href="services.html">Classes & Services</a></li>
									<li><a href="blog.html">Blog</a></li>
									<li><a href="contact.html">Contact</a></li>
								</ul>
							</nav>
							<div class="newsletter_container">
								<form action="#" id="newsletter_form" class="newsletter_form">
									<input type="text" class="newsletter_input" placeholder="Enter your email here" required="required">
									<button class="newsletter_button">go</button>
								</form>
							</div>
							<div class="copyright d-flex flex-row align-items-start justify-content-sm-end justify-content-center"><!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->
Copyright &copy;<script>document.write(new Date().getFullYear());</script> All rights reserved | This template is made with <i class="fa fa-heart-o" aria-hidden="true"></i> by <a href="https://colorlib.com" target="_blank">Colorlib</a>
<!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. --></div>
						</div>
						<div class="footer_image text-center"><img src="images/footer.png" alt=""></div>
					</div>
				</div>
			</div>
		</div>
	</footer>
</div>

<script src="js/jquery-3.2.1.min.js"></script>
<script src="styles/bootstrap-4.1.2/popper.js"></script>
<script src="styles/bootstrap-4.1.2/bootstrap.min.js"></script>
<script src="plugins/greensock/TweenMax.min.js"></script>
<script src="plugins/greensock/TimelineMax.min.js"></script>
<script src="plugins/scrollmagic/ScrollMagic.min.js"></script>
<script src="plugins/greensock/animation.gsap.min.js"></script>
<script src="plugins/greensock/ScrollToPlugin.min.js"></script>
<script src="plugins/easing/easing.js"></script>
<script src="plugins/parallax-js-master/parallax.min.js"></script>
<script src="https://maps.googleapis.com/maps/api/js?v=3.exp&key=AIzaSyCIwF204lFZg1y4kPSIhKaHEXMLYxxuMhA"></script>
<script src="js/contact.js"></script>
</body>
</html>

ayur/user/templates/user/login.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Sign Up - AYUR</title>
{% comment %} href="{% static 'expenses/style.css' %} {% endcomment %}
    <!-- Font Icon -->
    <link rel="stylesheet" href="{% static 'fonts/material-icon/css/material-design-iconic-font.min.css' %}">

    <!-- Main css -->
    
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
<link rel="stylesheet" href="{% static 'styles/style.css' %}">
</head>
<body>

    <div class="main">

        <section class="signup">
            <!-- <img src="images/signup-bg.jpg" alt=""> -->
            <div class="container">
                <div class="signup-content">
                    <form method="POST" id="signup-form" class="signup-form">
                    {% csrf_token %}
                        <h2 class="form-title">Create account</h2>
                        <div class="form-group">
                            <input type="text" name="username" placeholder="Username..." class="form-control">
                        </div>
                        <div class="form-group">
                            <input type="text" name="password" placeholder="Password..." class="form-control">
                        </div>
                        
                        <div class="form-group">
                            <input type="submit" name="submit" id="submit" class="form-submit" value="Login"/>
                        </div>
                    </form>
                </div>
                {% for message in messages %}
					<p id="messages">{{message}}</p>
				{% endfor %}			
		
				<div class="mt-4">
					<div class="d-flex justify-content-center links">
						Don't have an account? <a href="{% url 'user:register' %}" class="ml-2">Sign Up</a>
					</div>
			
				</div>
            </div>
        </section>

    </div>

    <!-- JS -->
    <script src="{% static 'vendor/jquery/jquery.min.js' %}"></script>
    {% comment %} <script src="{% static 'js/main.js' %}"></script> {% endcomment %}
</body><!-- This templates was made by Colorlib (https://colorlib.com) -->
</html>