ayur/ayur/urls.py
from django.conf import settings
from django.conf.urls.static import static
from user import views
from django.contrib import admin
from django.urls import path
from django.urls import path, include
urlpatterns = [
    path('',views.HomePage,name = "home"),
    path('about',views.aboutPage,name = "about"),
    path('admin/', admin.site.urls),
    path('user/', include('user.urls')),
    path('expenses/',include('expenses.urls')),
    path('hospital/',include('hospital.urls'))
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT) 

ayur/expenses/urls.py
from django.urls import path
from . import views

app_name = "expenses"

urlpatterns = [
    path('', views.home, name='home'),
    path('expense/<int:year_num>/<int:month_num>/', views.index, name='index'),
    path('expense/detail/<int:expense_id>/', views.detail, name='detail'),
    path('expense/add/', views.add_expense, name='add'),
    path('expense/update/<int:expense_id>/',
         views.update_expense,
         name='update'),
    path('expense/delete/<int:expense_id>',
         views.delete_expense,
         name='delete_expense'),
    path('expense/add_expense/', views.add_expense, name='add_expense'),
    path('expense/delete_expenses_monthly/<int:year_num>/<int:month_num>/',
         views.delete_expenses_monthly,
         name='delete_monthly'),
    path('expense/chart/<int:year_num>/<int:month_num>/',
         views.monthly_chart,
         name='monthly_chart'),
    path('expense/months/', views.image, name='image'),
    path('expense/months/<str:month>/', views.expmonth, name='month_exp'),
    path('expense/expense_summary/', views.expense_summary, name='expense_summary'),
]

ayur/expenses/models.py
from calendar import month
import datetime
from django.db import models
from django.utils import timezone
from user.models import *
# Create your models here.


class Expense(models.Model):
    userid=models.IntegerField(null=True)
    title = models.CharField(max_length=100)
    currency = models.CharField(max_length=100, null=True)
    description = models.CharField(max_length=200)
    amount = models.FloatField()
    payment_time = models.DateTimeField(null=True)
    dateOfPayment = models.CharField(max_length=100, default="None", null=True)
    month=models.IntegerField()
    year=models.IntegerField()

    def __str__(self) -> str:
        return str(self.amount)

    def was_payed_recently(self):
        now = timezone.now()

        day, month, year = now.day, now.month, now.year

        return now - datetime.timedelta(days=day) <= self.payment_time <= now

    class Meta:
        # ordering = ['-payment_time__day'] # do not have to use order_by (for daily aggregation)
        ordering = [
            '-payment_time'
        ]  # descending order --> most recent first, have to use order_by (for daily aggregation)

ayur/expenses/views.py
from re import S
from django.contrib.messages.constants import SUCCESS
from django.core.paginator import Paginator
from django.contrib import messages
from django.db.models import Sum
from django.contrib.auth.decorators import login_required
from datetime import datetime, timedelta
from calendar import monthrange
from django.http.response import HttpResponseRedirect
from django.urls import reverse
from django.shortcuts import get_list_or_404, get_object_or_404, render
from .models import Expense
from django.utils import timezone
from json import dumps
# import datetime
# Create your views here.


def home(request):
    now = timezone.now()
    year, month = now.year, now.month

    return HttpResponseRedirect(reverse('expenses:index', args=(
        year,
        month,
    )))


def index(request, year_num, month_num):
    this_time = timezone.now()
    this_day, this_month, this_year = this_time.day, this_time.month, this_time.year

    requested_expenses = Expense.objects.filter(userid=request.user.id)

    paginator = Paginator(requested_expenses, 6)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)

    requested_monthly_expense = sum(
        [expense.amount for expense in requested_expenses])
    print([expense.dateOfPayment for expense in requested_expenses])
    show_add_button = False

    # captured_date = datetime(year=year_num,
    #                          month=month_num,
    #                          day=1,
    #                          tzinfo=timezone.get_current_timezone())
    captured_date = datetime(year=year_num,
                             month=month_num,
                             day=1,
                             tzinfo=timezone.utc)

    if this_time - timedelta(days=this_day) <= captured_date <= this_time:
        show_add_button = True

    prev_exp_month = month_num - 1
    prev_exp_year = year_num

    if prev_exp_month == 0:
        prev_exp_month = 12
        prev_exp_year -= 1

    prev = {'month': prev_exp_month, 'year': prev_exp_year}

    last_monthly_expense = Expense.objects.filter(userid=request.user.id,
        payment_time__month=prev_exp_month,
        payment_time__year=prev_exp_year).aggregate(
            Sum('amount'))['amount__sum']

    if not last_monthly_expense:
        last_monthly_expense = 0

    progress = {}
    progress['color'] = {}
    if requested_monthly_expense > last_monthly_expense:
        progress['color']['bg'] = 'expended'
        progress['color']['text'] = 'light'
        progress['tail'] = 'more than'
    elif requested_monthly_expense < last_monthly_expense:
        progress['color']['bg'] = 'saved'
        progress['color']['text'] = 'dark'
        progress['tail'] = 'less than'
    else:
        progress['color']['bg'] = 'same'
        progress['color']['text'] = 'light'
        progress['tail'] = 'Same as'

    progress['tail'] += ' last month'
    progress['difference'] = abs(requested_monthly_expense -
                                 last_monthly_expense)

    data = {
        # 'expenses': curr_expenses,
        'prev': prev,
        'curr_monthly_expense': requested_monthly_expense,
        'last_monthly_expense': last_monthly_expense,
        'progress': progress,
        'show_add_button': show_add_button,
        'captured_date': captured_date,
        'page_obj': page_obj
    }
    return render(request, 'expenses/index.html', context=data)


def detail(request, expense_id):
    expense_object = get_object_or_404(Expense, id=expense_id)
    data = {'expense': expense_object}
    return render(request, 'expenses/detail.html', context=data)


def add_expense(request):
    import requests

    if request.method == 'POST':
        userid=request.user.id
        print(userid)
        title = request.POST.get('title')
        currency = request.POST.get('currency')
        desc = request.POST.get('desc')
        price = float(request.POST.get('price'))
        date = request.POST.get('date')
        month=int(date[5:7])
        year=int(date[0:4])
        # print(f"laaaaaaaaaaaaaaaaalalala {month}{year}")

        if currency == "rupees": pass

        elif currency == "dollar":
            x = requests.get('https://free.currconv.com/api/v7/convert?q=USD_INR&compact=ultra&apiKey=a3cdec3932699146c5e3')
            print(f"$$$$$$$$$$${x.json}")
            # price *= int(x.json()['USD_INR'])
            print(f"price!!!! {price}")

        elif currency == "euros":
            x = requests.get('https://free.currconv.com/api/v7/convert?q=EUR_INR&compact=ultra&apiKey=a3cdec3932699146c5e3')

            price *= int(x.json()['EUR_INR'])

        new_expense = Expense(userid=userid,
                              title=title,
                              currency = currency,
                              description=desc,
                              amount=price,
                              payment_time=timezone.now(),
                              dateOfPayment = date,
                              month=month,
                              year=year
                              )

        new_expense.save()

        messages.add_message(request,
                             level=SUCCESS,
                             message='Successfully <b>added</b> the expense!',
                             extra_tags='safe')

        return HttpResponseRedirect(reverse('expenses:home'))

    return render(request, 'expenses/add_expense.html')


def delete_expense(request, expense_id):
    if request.method == 'POST':
        expense = get_object_or_404(Expense, id=expense_id)
        expense_time = expense.payment_time
        month, year = expense_time.month, expense_time.year

        expense.delete()

        messages.add_message(
            request,
            level=SUCCESS,
            message='Successfully <b>deleted</b> the requested item!',
            extra_tags='safe')

        return HttpResponseRedirect(
            reverse('expenses:index', args=(year, month)))

    else:
        messages.add_message(request,
                             level=messages.ERROR,
                             message='Invalid request to delete an item!',
                             extra_tags='safe')

        return HttpResponseRedirect(reverse('expenses:home'))


def update_expense(request, expense_id):
    if request.method == 'POST':
        expense = get_object_or_404(Expense, id=expense_id)
        title = request.POST.get('title')
        description = request.POST.get('desc')
        amount = request.POST.get('price')

        expense_time = expense.payment_time
        year, month = expense_time.year, expense_time.month

        if title:
            expense.title = title
        if description:
            expense.description = description
        if amount:
            expense.amount = amount

        expense.save()

        messages.add_message(
            request,
            level=SUCCESS,
            message='Successfully <b>updated</b> the expense!',
            extra_tags='safe')

        return HttpResponseRedirect(
            reverse('expenses:index', args=(
                year,
                month,
            )))

    expense = get_object_or_404(Expense, id=expense_id)

    return render(request, 'expenses/update_expense.html', {
        'expense': expense,
    })


def monthly_chart(request, year_num, month_num):
    labels = []
    data = []

    category_dictionary = {}
    date_dictionary = {}

    # print(list(Expense.objects.values()))

    for expense in Expense.objects.values():
        category = expense['title']

        if category not in category_dictionary:
            category_dictionary[category] = expense['amount']
        else:
            category_dictionary[category] += expense['amount']

        # print(expense)

    for expense in Expense.objects.values():
        category = expense['dateOfPayment']

        if category not in date_dictionary:
            date_dictionary[category] = expense['amount']
        else:
            date_dictionary[category] += expense['amount']

    expenses_list = Expense.objects.values('payment_time__day')\
        .order_by('payment_time__day')\
        .annotate(total_expenses=Sum('amount'))\
        .filter(
            payment_time__month=month_num,
            payment_time__year=year_num
        )

    for expense in expenses_list:
        expense_day = expense.get('payment_time__day')
        expense_date = datetime(year=year_num, month=month_num, day=expense_day)
        labels.append(expense_date)
        data.append(expense.get('total_expenses'))

    # print(list(category_dictionary.keys()))
    # print(category_dictionary)

    category_data = dumps(category_dictionary)
    date_data = dumps(date_dictionary)

    return render(
        request, 'expenses/month_chart.html', {
            'labels': labels,
            'data': data,
            'req_date': datetime(year=year_num, month=month_num, day=1),
            'category_data' : category_data,
            "date_data":date_data,
            "heading" : "daily",
            "head" : "always"
        })



def expmonth(request,month):
        k=['tp','January','February','March','April','May','June','July','August','September','October','November','December']
        l=k.index(month)
        exp=Expense.objects.filter(userid=request.user.id,month=l)
        paginator = Paginator(exp, 6)
        page_number = request.GET.get('page')
        page_obj = paginator.get_page(page_number)
        s=0
        for expense in page_obj:
            print(expense)
            s=s+(expense.amount)
        data={
            'page_obj':page_obj,
            'month':month,
            'total_exp':s
        }
        # print(page_obj)
        
        return render(request, 'expenses/monthly.html', context=data)




def delete_expenses_monthly(request, year_num, month_num):
    if request.method == 'POST':
        expenses = get_list_or_404(Expense,

ayur/expenses/templates/expenses/image.html
{% extends "expenses/base.html" %}

{% load static %}

{% load humanize %}

{% block content %}
    <label for="formFileDisabled" class="form-label">Disabled file input example</label>
    <input class="form-control" type="file" id="formFileDisabled" />
    <a class="btn btn-outline-danger mt-5 float-end me-5" href="#" role="button" data-bs-toggle="modal" data-bs-target="#deleteAllModal">Submit</a>
{% endblock %}

ayur/expenses/templates/expenses/index.html
{% extends "expenses/base.html" %}

{% load static %}

{% load humanize %}

{% block content %}
<!-- Home -->

	<div class="home">
    <div class="background_image" style="background-image: url({% static 'expenses/ex.jpg' %}); filter: brightness(50%)"></div>
		{% comment %} <div class="background_image" style="background: url({% static 'expenses/contact.jpg' %})"></div> {% endcomment %}
		<div class="overlay"></div>
		<div class="home_container">
			<div class="container">
				<div class="row">
					<div class="col">
						<div class="home_content">
							<div class="home_title">📚 Expense Diary</div>
							<div class="home_subtitle">Keep a track of all your expenses!</div>
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>
    {% comment %}  style="margin-top:200px;" {% endcomment %}
    <div class="container mother-container">
    {% comment %} <h1 style="margin-top:100px;">
        <span class="badge bg-dark apptitle">📚 Expense Diary</span>
    </h1> {% endcomment %}

    <h3 class="mt-5">Your Expenses :
        {% comment %} <span class="text-primary year-month">{{ captured_date|date:'F, Y' }}</span> {% endcomment %}
    </h3>

    <h4>
        Monthly Expense:
        <span
            class="badge month-stats text-dark">
            <!-- bg-warning text-dark -->
            Rs.
            {% if curr_monthly_expense > 1000000 %}
                {{ curr_monthly_expense|intword }}
            {% else %}
                {{ curr_monthly_expense|intcomma }}
            {% endif %}
        </span>
        <span
            class="badge month-stats text-{{ progress.color.text }} badge-{{ progress.color.bg }}">
            <!-- bg-{{progress.color}} -->
            {% if progress.color.bg != 'same' %}
                Rs.
                {% if progress.difference > 1000000 %}
                    {{ progress.difference|intword }}
                {% else %}
                    {{ progress.difference|intcomma }}
                {% endif %}
            {% endif %}
            {{ progress.tail }}
        </span>
    </h3>


    {% if show_add_button %}
        <a class="btn btn-outline-dark mt-5 me-md-3 greenbg" href="{% url 'expenses:add' %}" role="button">💰 Add Expense</a>
        <a class="btn btn-outline-dark mt-5 me-md-3 greenbg" href="{% url 'expenses:image' %}" role="button" >💸 View Monthly records</a>
        
    {% endif %}

    {% if not show_add_button %}
        <a class="btn btn-outline-primary mt-5 me-3" href="{% url 'expenses:home' %}" role="button">🏡 Go back to home</a>
    {% endif %}

    {% if page_obj %}
        <a class="btn btn-outline-primary mt-5" href="{% url 'expenses:monthly_chart' captured_date.year captured_date.month %}" role="button">📊 Your Report
        </a>
        <a class="btn btn-outline-danger mt-5 float-end me-5" href="#" role="button" data-bs-toggle="modal" data-bs-target="#deleteAllModal">
            Delete all expenses
            <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-exclamation-circle-fill" viewBox="0 0 16 16">
                <path d="M16 8A8 8 0 1 1 0 8a8 8 0 0 1 16 0zM8 4a.905.905 0 0 0-.9.995l.35 3.507a.552.552 0 0 0 1.1 0l.35-3.507A.905.905 0 0 0 8 4zm.002 6a1 1 0 1 0 0 2 1 1 0 0 0 0-2z"/>
            </svg>
        </a>

    {% endif %}


    <hr
        class="mt-5">

        <!-- change expenses:page_obj -->
        {% if not page_obj %}
            <h1 class="shrugged text-center mt-5">¯\_(ツ)_/¯</h1>
            <h5 class="mt-4 text-center shrugged-caption">No expenses were found</h5>

        {% else %}


            <div
                class="row row-cols-3 row-cols-sm-3 g-4 mt-3">
                <!-- change expenses:page_obj -->
                {% for expense in page_obj %}
                    <div class="col">
                        <div class="card text-dark bg-transparent mx-auto mb-3" style="max-width: 22rem;">

                            <div class="card-header amount">
                                Rs.
                                {% if expense.amount > 1000000 %}
                                    {{ expense.amount|intword }}
                                {% else %}
                                    {{ expense.amount|intcomma }}
                                {% endif %}
                                <a href="{% url 'expenses:update' expense.id %}" class="editIcon link-primary float-end">
                                    <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-pencil" viewBox="0 0 16 16">
                                        <path fill-rule="evenodd" d="M12.146.146a.5.5 0 0 1 .708 0l3 3a.5.5 0 0 1 0 .708l-10 10a.5.5 0 0 1-.168.11l-5 2a.5.5 0 0 1-.65-.65l2-5a.5.5 0 0 1 .11-.168l10-10zM11.207 2.5L13.5 4.793 14.793 3.5 12.5 1.207 11.207 2.5zm1.586 3L10.5 3.207 4 9.707V10h.5a.5.5 0 0 1 .5.5v.5h.5a.5.5 0 0 1 .5.5v.5h.293l6.5-6.5zm-9.761 5.175l-.106.106-1.528 3.821 3.821-1.528.106-.106A.5.5 0 0 1 5 12.5V12h-.5a.5.5 0 0 1-.5-.5V11h-.5a.5.5 0 0 1-.468-.325z"/>
                                    </svg>
                                </a>
                            </div>
                            <div class="card-body">
                                <h5 class="card-title ctitle" id="cardid">{{ expense.title|truncatechars:25 }}</h5>
                                <p class="card-text">{{ expense.description|truncatechars:25 }}</p>
                                <a href="{% url 'expenses:detail' expense.id %}" class="btn btn-outline-primary btn-sm">View Details</a>

                                <!-- Form for deleting an expense item -->
                                <form class="float-end" action="{% url 'expenses:delete_expense' expense.id %}" method="post">
                                    {% csrf_token %}
                                    <button class="btn btn-outline-danger btn-sm float-end" type="submit" data-bs-toggle="tooltip" data-bs-placement="right" title="Delete">
                                        <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-trash-fill" viewBox="0 0 16 16">
                                            <path fill-rule="evenodd" d="M2.5 1a1 1 0 0 0-1 1v1a1 1 0 0 0 1 1H3v9a2 2 0 0 0 2 2h6a2 2 0 0 0 2-2V4h.5a1 1 0 0 0 1-1V2a1 1 0 0 0-1-1H10a1 1 0 0 0-1-1H7a1 1 0 0 0-1 1H2.5zm3 4a.5.5 0 0 1 .5.5v7a.5.5 0 0 1-1 0v-7a.5.5 0 0 1 .5-.5zM8 5a.5.5 0 0 1 .5.5v7a.5.5 0 0 1-1 0v-7A.5.5 0 0 1 8 5zm3 .5a.5.5 0 0 0-1 0v7a.5.5 0 0 0 1 0v-7z"/>
                                        </svg>
                                    </button>
                                </form>

                            </div>
                        </div>
                    </div>
                {% endfor %}

            </div>

        {% endif %}

        <div class="pagination text-center mx-auto d-block" style="max-width: 300px;">
            <span class="step-links">

                <span class="mt-5 d-block">
                    {% if page_obj.has_previous %}
                        <a href="?page=1" class="me-3">&laquo; first</a>
                        <a href="?page={{ page_obj.previous_page_number }}" class="me-3">previous</a>
                    {% endif %}


                    {% if page_obj.has_next %}
                        <a href="?page={{ page_obj.next_page_number }}" class="me-3">next</a>
                        <a href="?page={{ page_obj.paginator.num_pages }}">last &raquo;</a>
                    {% endif %}
                </span>

                <span class="current d-block mt-3 mb-3">
                    <em>Page
                        {{ page_obj.number }}
                        of
                        {{ page_obj.paginator.num_pages }}</em>.
                </span>

            </span>
        </div>

        <!-- Vertically centered modal -->
        <div class="modal fade" id="deleteAllModal" data-bs-keyboard="false" tabindex="-1" aria-labelledby="staticBackdropLabel" aria-hidden="true">
            <div class="modal-dialog modal-dialog-centered">
                <div class="modal-content">
                    <div class="modal-header">
                        <h5 class="modal-title" id="staticBackdropLabel">Delete all expenses of current month</h5>
                        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                    </div>
                    <div class="modal-body">
                        This action is irreversible and will delete all the expenses that you added this month
                    </div>
                    <div class="modal-footer">
                        <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Cancel</button>
                        <form action="{% url 'expenses:delete_monthly' captured_date.year captured_date.month %}" method="post">
                            {% csrf_token %}
                            <button class="btn btn-danger" type="submit" name="delete_all" value="confirmed">
                                Yes, I wish to Proceed
                            </button>
                        </form>
                    </div>
                </div>
            </div>
        </div>


    {% endblock %}
</div>

ayur/expenses/templates/expenses/index1.html
{% extends "expenses/base.html" %}

{% load static %}

{% load humanize %}

{% block content %}
<!-- Home -->

	<div class="home">
    <div class="background_image" style="background-image: url({% static 'expenses/ex.jpg' %}); filter: brightness(50%)"></div>
		{% comment %} <div class="background_image" style="background: url({% static 'expenses/contact.jpg' %})"></div> {% endcomment %}
		<div class="overlay"></div>
		<div class="home_container">
			<div class="container">
				<div class="row">
					<div class="col">
						<div class="home_content">
							<div class="home_title">📚 Expense Diary</div>
							<div class="home_subtitle">Keep a track of all your expenses!</div>
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>
    
    {% comment %}  style="margin-top:200px;" {% endcomment %}
    <div class="container mother-container">
    <h3> Choose a month:</h3>
    {% comment %} <h1 style="margin-top:100px;">
        <span class="badge bg-dark apptitle">📚 Expense Diary</span>
    </h1> {% endcomment %}

<hr
        class="mt-5">

        <!-- change expenses:page_obj -->
        {% comment %} {% if not page_obj %}
            <h1 class="shrugged text-center mt-5">¯\_(ツ)_/¯</h1>
            <h5 class="mt-4 text-center shrugged-caption">No expenses were found</h5>

        {% else %} {% endcomment %}

{% comment %} <h5 class="card-title ctitle" id="cardid">{{ m.1}}</h5> {% endcomment %}
          
            <div
                class="row row-cols-3 row-cols-sm-3 g-4 mt-3">
                <!-- change expenses:page_obj -->
                {% for month in m %}
                    <div class="col">
                        <div class="card text-dark bg-transparent mx-auto mb-3" style="max-width: 22rem;">

                            <div class="card-header amount">
                                Expenses for month :
                            </div>
                            <div class="card-body">
                                <h5 class="card-title ctitle" id="cardid">{{ month}}</h5>
                                {% comment %} <p class="card-text">{{ expense.description|truncatechars:25 }}</p> {% endcomment %}
                                <a href="{% url 'expenses:month_exp' month%}" class="btn btn-outline-primary btn-sm">View Details</a>

                                {% comment %} <!-- Form for deleting an expense item -->
                                <form class="float-end" action="{% url 'expenses:delete_expense' expense.id %}" method="post">
                                    {% csrf_token %}
                                    <button class="btn btn-outline-danger btn-sm float-end" type="submit" data-bs-toggle="tooltip" data-bs-placement="right" title="Delete">
                                        <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-trash-fill" viewBox="0 0 16 16">
                                            <path fill-rule="evenodd" d="M2.5 1a1 1 0 0 0-1 1v1a1 1 0 0 0 1 1H3v9a2 2 0 0 0 2 2h6a2 2 0 0 0 2-2V4h.5a1 1 0 0 0 1-1V2a1 1 0 0 0-1-1H10a1 1 0 0 0-1-1H7a1 1 0 0 0-1 1H2.5zm3 4a.5.5 0 0 1 .5.5v7a.5.5 0 0 1-1 0v-7a.5.5 0 0 1 .5-.5zM8 5a.5.5 0 0 1 .5.5v7a.5.5 0 0 1-1 0v-7A.5.5 0 0 1 8 5zm3 .5a.5.5 0 0 0-1 0v7a.5.5 0 0 0 1 0v-7z"/>
                                        </svg>
                                    </button>
                                </form> {% endcomment %}

                            </div>
                        </div>
                    </div>
                {% endfor %}

            </div>

        {% comment %} {% endif %} {% endcomment %}
        {% comment %} <!-- Vertically centered modal -->
        <div class="modal fade" id="deleteAllModal" data-bs-keyboard="false" tabindex="-1" aria-labelledby="staticBackdropLabel" aria-hidden="true">
            <div class="modal-dialog modal-dialog-centered">
                <div class="modal-content">
                    <div class="modal-header">
                        <h5 class="modal-title" id="staticBackdropLabel">Delete all expenses of current month</h5>
                        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                    </div>
                    <div class="modal-body">
                        This action is irreversible and will delete all the expenses that you added this month
                    </div>
                    <div class="modal-footer">
                        <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Cancel</button>
                        <form action="{% url 'expenses:delete_monthly' captured_date.year captured_date.month %}" method="post">
                            {% csrf_token %}
                            <button class="btn btn-danger" type="submit" name="delete_all" value="confirmed">
                                Yes, I wish to Proceed
                            </button>
                        </form>
                    </div>
                </div>
            </div>
        </div> {% endcomment %}


    {% endblock %}
</div>

ayur/expenses/templates/expenses/message_update.html
{% if messages %}

    {% for message in messages %}


        <div class="alert alert-{{ message.level_tag|lower }} alert-dismissible fade show mt-4" role="alert">
            {% if 'safe' in message.tags %}
                {{ message|safe }}
            {% else %}
                {{ message }}
            {% endif %}

            <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>

        </div>

    {% endfor %}
{% endif %}

ayur/expenses/templates/expenses/update_expense.html
{% extends "expenses/base.html" %}

{% load static %}

{% load humanize %}

{% block title %}
    Add Expense
{% endblock %}

{% block content %}

    <div class="container mt-5" style="max-width: 50%;">
        <h4 class="mb-5 text-center">Update expense #{{ expense.id }}
        </h4>

        <form action="{% url 'expenses:update' expense.id %}" method="post">

            {% csrf_token %}

            <div class="row mb-3">
                <label for="inputText3" class="col-sm-2 col-form-label">Paid for</label>
                <div class="col-sm-10">
                    <input type="text" class="form-control update-input" name="title" placeholder="{{ expense.title }}" id="inputText3"></div>
                </div>

                <div class="row mb-3">
                    <label for="inputDesc3" class="col-sm-2 col-form-label">Description</label>

                    <div class="col-sm-10">
                        <textarea class="form-control update-input" rows="3" name="desc" id="inputDesc3" maxlength="200" placeholder="{{ expense.description }}"></textarea>

                    </div>
                </div>

                <div class="row mb-3">
                    <label for="inputPrice3" class="col-sm-2 col-form-label">Amount Paid</label>
                    <div class="col-sm-10">
                        <input type="number" class="form-control update-input" name="price" placeholder="{{ expense.amount }}" id="inputPrice3"></div>
                    </div>

                    <a class="btn btn-secondary float-end" href="{% url 'expenses:home' %}" role="button">Cancel</a>
                    <button type="submit" class="btn btn-primary float-end me-3">Update</button>

                </form>
            </div>


        {% endblock %}